version: 2

project_name: clickup

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/clickup
    binary: clickup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/triptechtravel/clickup-cli/internal/build.Version={{.Version}}
      - -X github.com/triptechtravel/clickup-cli/internal/build.Commit={{.Commit}}
      - -X github.com/triptechtravel/clickup-cli/internal/build.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: triptechtravel
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/triptechtravel/clickup-cli"
    description: "CLI tool for ClickUp task management with GitHub integration"
    license: "MIT"
    install: |
      bin.install "clickup"
    test: |
      system "#{bin}/clickup", "version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: triptechtravel
    name: clickup-cli
