// gen-docs generates CLI reference documentation from the Cobra command tree.
//
// Usage:
//
//	go run ./cmd/gen-docs [--out DIR]
//
// By default, it writes Starlight-compatible markdown files to docs/src/content/docs/reference/.
// Each command gets its own page with frontmatter, flags, and examples.
//
// It also generates docs/src/content/docs/commands.md — a categorized command
// overview page with links to each reference page.
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/triptechtravel/clickup-cli/internal/iostreams"
	"github.com/triptechtravel/clickup-cli/pkg/cmd/root"
	"github.com/triptechtravel/clickup-cli/pkg/cmdutil"
)

func main() {
	outDir := "docs/src/content/docs/reference"
	if len(os.Args) > 2 && os.Args[1] == "--out" {
		outDir = os.Args[2]
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		log.Fatalf("failed to create output directory: %v", err)
	}

	// Build the command tree. Auth is not needed for doc generation.
	ios := iostreams.System()
	f := cmdutil.NewFactory(ios)
	rootCmd := root.NewCmdRoot(f)
	rootCmd.DisableAutoGenTag = true

	// Prepend Starlight frontmatter to each generated file.
	prepender := func(filename string) string {
		name := filepath.Base(filename)
		base := strings.TrimSuffix(name, filepath.Ext(name))

		// Convert "clickup_task_view" to "clickup task view"
		title := strings.ReplaceAll(base, "_", " ")

		return fmt.Sprintf(`---
title: "%s"
description: "Auto-generated reference for %s"
---

`, title, title)
	}

	// Link handler for cross-references between command pages.
	linkHandler := func(name string) string {
		base := strings.TrimSuffix(name, filepath.Ext(name))
		return "/clickup-cli/reference/" + strings.ToLower(base) + "/"
	}

	if err := doc.GenMarkdownTreeCustom(rootCmd, outDir, prepender, linkHandler); err != nil {
		log.Fatalf("failed to generate docs: %v", err)
	}

	// Post-process: remove the duplicate ## heading that cobra generates
	// (Starlight already renders the title from frontmatter).
	entries, _ := os.ReadDir(outDir)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		fpath := filepath.Join(outDir, entry.Name())
		data, err := os.ReadFile(fpath)
		if err != nil {
			continue
		}
		content := string(data)
		// The cobra-generated heading is "## clickup ..." right after frontmatter.
		// Remove it plus the short description line that follows.
		lines := strings.Split(content, "\n")
		var out []string
		skip := false
		for i, line := range lines {
			if !skip && strings.HasPrefix(line, "## clickup") {
				skip = true
				continue
			}
			if skip {
				// Skip the blank line and short description that follow the heading.
				if line == "" || (i > 0 && strings.HasPrefix(lines[i-1], "## clickup")) {
					continue
				}
				skip = false
			}
			out = append(out, line)
		}
		_ = os.WriteFile(fpath, []byte(strings.Join(out, "\n")), 0644)
	}

	fmt.Printf("Generated %d reference pages in %s\n", len(entries), outDir)

	// Generate commands.md overview page.
	commandsPath := filepath.Join(filepath.Dir(outDir), "commands.md")
	if err := genCommandsPage(rootCmd, commandsPath); err != nil {
		log.Fatalf("failed to generate commands.md: %v", err)
	}
	fmt.Printf("Generated commands overview at %s\n", commandsPath)
}

// commandCategory groups commands for the overview page.
type commandCategory struct {
	label    string
	commands []commandEntry
}

type commandEntry struct {
	use   string // display name, e.g. "task view"
	short string // short description from Cobra
	slug  string // reference page slug, e.g. "clickup_task_view"
}

func genCommandsPage(rootCmd *cobra.Command, path string) error {
	categories := collectCategories(rootCmd)

	var b strings.Builder
	b.WriteString(`---
title: Command reference
description: Overview of all clickup CLI commands, grouped by category.
---

`)
	b.WriteString("<!-- This file is auto-generated by gen-docs. Do not edit manually. -->\n\n")
	b.WriteString("All commands are invoked as subcommands of `clickup`. Run `clickup --help` for a summary, or `clickup <command> --help` for details on any command.\n\n")
	b.WriteString("Every command that produces output supports `--json` for machine-readable output, `--jq` for inline filtering, and `--template` for Go template formatting.\n\n")
	b.WriteString("Flag details, examples, and options for each command are in the auto-generated [Reference](/clickup-cli/reference/clickup/) pages.\n\n")

	for i, cat := range categories {
		if i > 0 {
			b.WriteString("---\n\n")
		}
		b.WriteString(fmt.Sprintf("## %s\n\n", cat.label))
		b.WriteString("| Command | Description |\n")
		b.WriteString("|---------|-------------|\n")
		for _, cmd := range cat.commands {
			b.WriteString(fmt.Sprintf("| [`%s`](/clickup-cli/reference/%s/) | %s |\n", cmd.use, cmd.slug, cmd.short))
		}
		b.WriteString("\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// collectCategories walks the command tree and organises leaf commands into
// categories that match the docs site sidebar.
func collectCategories(rootCmd *cobra.Command) []commandCategory {
	// Map top-level command names to category labels and ordering.
	type catDef struct {
		label string
		order int
	}
	catMap := map[string]catDef{
		"task":       {"Task management", 0},
		"doc":        {"Docs", 1},
		"status":     {"Status & fields", 3},
		"field":      {"Status & fields", 3},
		"tag":        {"Status & fields", 3},
		"comment":    {"Comments", 4},
		"attachment": {"Attachments", 4},
		"link":       {"Git & GitHub integration", 5},
		"sprint":     {"Sprints", 6},
		"inbox":      {"Workspace", 7},
		"member":     {"Workspace", 7},
		"space":      {"Workspace", 7},
		"auth":       {"Setup & utilities", 8},
		"version":    {"Setup & utilities", 8},
		"completion": {"Setup & utilities", 8},
	}

	// Sub-groups within task for better organisation.
	taskSubgroups := map[string]string{
		"time":       "Time tracking",
		"dependency": "Dependencies & checklists",
		"checklist":  "Dependencies & checklists",
	}

	// Collect entries by category label, preserving insertion order.
	type bucket struct {
		label   string
		order   int
		entries []commandEntry
	}
	bucketMap := make(map[string]*bucket)
	var bucketOrder []string

	addEntry := func(label string, order int, entry commandEntry) {
		b, ok := bucketMap[label]
		if !ok {
			b = &bucket{label: label, order: order}
			bucketMap[label] = b
			bucketOrder = append(bucketOrder, label)
		}
		b.entries = append(b.entries, entry)
	}

	for _, topCmd := range rootCmd.Commands() {
		if !topCmd.IsAvailableCommand() || topCmd.IsAdditionalHelpTopicCommand() {
			continue
		}

		cd, ok := catMap[topCmd.Name()]
		if !ok {
			continue
		}

		subs := topCmd.Commands()
		if len(subs) == 0 {
			// Leaf command at top level (e.g. inbox, version).
			addEntry(cd.label, cd.order, commandEntry{
				use:   topCmd.Name(),
				short: topCmd.Short,
				slug:  "clickup_" + topCmd.Name(),
			})
			continue
		}

		for _, sub := range subs {
			if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
				continue
			}

			// Check for nested sub-sub-commands (e.g. task time log, task checklist add).
			subSubs := sub.Commands()
			if len(subSubs) > 0 {
				for _, ss := range subSubs {
					if !ss.IsAvailableCommand() || ss.IsAdditionalHelpTopicCommand() {
						continue
					}

					displayName := topCmd.Name() + " " + sub.Name() + " " + ss.Name()
					slug := "clickup_" + topCmd.Name() + "_" + sub.Name() + "_" + ss.Name()

					label := cd.label
					if topCmd.Name() == "task" {
						if sg, ok := taskSubgroups[sub.Name()]; ok {
							label = sg
						}
					}

					addEntry(label, cd.order, commandEntry{
						use:   displayName,
						short: ss.Short,
						slug:  slug,
					})
				}
			} else {
				displayName := topCmd.Name() + " " + sub.Name()
				slug := "clickup_" + topCmd.Name() + "_" + sub.Name()

				label := cd.label
				if topCmd.Name() == "task" {
					if sg, ok := taskSubgroups[sub.Name()]; ok {
						label = sg
					}
				}

				addEntry(label, cd.order, commandEntry{
					use:   displayName,
					short: sub.Short,
					slug:  slug,
				})
			}
		}
	}

	// Sort buckets by order.
	sorted := make([]commandCategory, 0, len(bucketOrder))
	for _, label := range bucketOrder {
		b := bucketMap[label]
		sorted = append(sorted, commandCategory{label: b.label, commands: b.entries})
	}
	// Stable sort by order field.
	for i := 1; i < len(sorted); i++ {
		for j := i; j > 0 && bucketMap[sorted[j].label].order < bucketMap[sorted[j-1].label].order; j-- {
			sorted[j], sorted[j-1] = sorted[j-1], sorted[j]
		}
	}

	return sorted
}
